### ISSUE TITLE
docs(spec/package): Suteraパッケージのアバターについて (yamlフォーマット)

### ISSUE THREAD

**Issue by AsPulse** [SuteraVR/Specifications#38]

**Comment by See2et** [comment]
- boneと関節の結び付き、トラッキングポイント

- 衣装周りの話
https://note.com/masakikado/n/ne2799a88b6b0
https://www.sidefx.com/ja/docs/houdini/nodes/sop/gltf.html

```yaml
objects:
  - id: body
    model: ....
  - id: costume
    model: ....
  - id: へいろー
    model: ...

tracking_assignments:
  - bone:
      id: body
      model: left_leg_1
    tracking_point: LLegTop
  - bone:
      id: body
      model: right_leg_1
      apply_only:
        - transform_all # 位置のみ同期
    tracking_point: RLegTop
  - copy_relative_transform: # 位置をモデルに同期
      model: へいろー
    tracking_point: Head
```
